#!/bin/sh
node generate-index.js

# Get the current Git repository name
REPO_NAME=$(basename -s .git `git config --get remote.origin.url`)

# Create a new README.md file with the script and link tags as markdown code blocks
echo "```html" > README.md
echo "<script src=\"https://${REPO_NAME}.vercel.app/dist/index.js\"></script>" >> README.md
echo "```" >> README.md
echo "" >> README.md
echo "```html" >> README.md
echo "<link rel=\"stylesheet\" href=\"https://${REPO_NAME}.vercel.app/dist/index.css\">" >> README.md
echo "```" >> README.md
